# Generated by Django 2.1.1 on 2018-10-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20181002_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lesson',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
