# Generated by Django 2.1.1 on 2018-10-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20181015_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lesson',
            field=models.CharField(default='models.slug', max_length=100),
        ),
    ]
