# Generated by Django 2.1.1 on 2018-11-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='lesson',
            field=models.CharField(default='Type the name of lesson Case sensitive', max_length=100),
        ),
    ]
