# Generated by Django 2.1.1 on 2018-11-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20181102_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='lesson',
        ),
    ]
