# Generated by Django 2.1.1 on 2018-11-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20181104_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lesson',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
